baseurl: /
blackfriday:
  extensionsmask:
  - autolink
  fractions: false
  smartypants: false
languageCode: en-us
metaDataFormat: yaml
title: Caddy - The HTTP/2 Web Server with Fully Managed TLS
uglyURLs: true
